pages:
  - 🐍曲集锦:
    - path: song-releases
    - src: pages/song-releases.md
    - author: Snakes
    - date: 2026/08/08
    - tags: [Aug 2026]
  - 异或最小值的性质:
    - path: minimum-under-linear-basis
    - src: pages/minimum-under-linear-basis.md
    - author: Snakes
    - date: 2026/01/20
    - tags: [Jan 2026, Linear Basis, Tutorial]
  - 🐍题集锦:
    - path: problem-settings
    - src: pages/problem-settings.md
    - author: Snakes
    - date: 2025/12/31
    - tags: [Dec 2025, Codeforces]
  - SHA256 以 114514 开头的字符串:
    - path: sha256-114514
    - src: pages/sha256-114514.md
    - author: Snakes
    - date: 2024/05/17
    - tags: [May 2024, SHA256]
  - BCPC 2020 预赛题解:
    - path: bcpc-2020-preliminary
    - src: pages/bcpc-2020-preliminary.md
    - author: Snakes
    - date: 2020/12/02
    - tags: [Dec 2020, BCPC 2020, Tutorial]
  - Möbius Inversion and Dirichlet Convolution:
    - path: mobius-inversion-dirichlet-convolution
    - src: pages/mobius-inversion-dirichlet-convolution.md
    - author: Snakes
    - date: 2018/05/20
    - tags: [May 2018, Möbius Inversion, Dirichlet Convolution]
